docs: libraries-bom 13.3.0
googleapis/google-cloud-java pull request #7370
Opened 2020-10-26 21:13 UTC by suztomo

docs: libraries-bom 13.3.0

Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for context and/or discussion)

2020-10-26 21:20 UTC, elharo requested changes
13.3.0

2020-10-27 02:53 UTC, lesv approved these changes

2020-10-27 13:52 UTC, elharo requested changes

2020-10-27 13:52 UTC, elharo commented on TROUBLESHOOTING.md
> +  `com.google.cloud:libraries-bom:12.3.0` (or a more recent version) and use that to
13.3.0

2020-10-27 14:44 UTC, suztomo reviewed
@elharo PTAL.

2020-10-27 14:44 UTC, suztomo commented on TROUBLESHOOTING.md
> +  `com.google.cloud:libraries-bom:12.3.0` (or a more recent version) and use that to
Fixed

2020-10-27 14:44 UTC, suztomo commented on TROUBLESHOOTING.md
> +        <version>12.3.0</version>
Fixed.

2020-10-27 16:07 UTC, elharo approved these changes

2020-10-29 03:32 UTC, merged