docs: libraries-bom 20.5.0
googleapis/google-cloud-java pull request #7565
Opened 2021-05-26 12:19 UTC by elharo

@suztomo

2021-05-26 12:31 UTC, suztomo approved these changes

2021-05-26 12:32 UTC, suztomo requested changes
Line 103 also needs to change.

2021-05-26 16:19 UTC, elharo reviewed
done

2021-05-27 11:45 UTC, suztomo approved these changes

2021-05-27 13:29 UTC, merged