chore: Adding release-please annotations
googleapis/google-cloud-java pull request #8469
Opened 2022-09-27 18:45 UTC by ddixit14

2022-09-27 18:48 UTC, suztomo requested changes
Can you remove "-parent" suffix from the key?

By convention, we don't use "-parent" as key. So "google-cloud-java" is a good key.
https://github.com/googleapis/java-accessapproval/blob/main/versions.txt

2022-09-27 19:07 UTC, meltsufin approved these changes

2022-09-27 19:07 UTC, meltsufin commented on versions.txt
> +google-cloud-java:0.0.0:0.0.1-SNAPSHOT
Should we start with `1.0.0-SNAPSHOT`?

2022-09-27 20:50 UTC, suztomo approved these changes

2022-09-28 13:43 UTC, ddixit14 commented on versions.txt
> +google-cloud-java:0.0.0:0.0.1-SNAPSHOT
Done.

2022-09-28 14:41 UTC, merged