feat: [maps-mapsplatformdatasets] new module for maps-mapsplatformdatasets
googleapis/google-cloud-java pull request #9119
Opened 2023-02-14 15:21 UTC by emmileaf

Initial generation for new mapsplatformdatasets client library: 

```
python3.9 generation/new_client/new-client.py generate \
  --api_shortname=maps-mapsplatformdatasets \
  --proto-path=google/maps/mapsplatformdatasets \
  --name-pretty="Maps Platform Datasets API" \
  --product-docs="https://developers.google.com/maps/documentation" \
  --api-description="Maps Platform Datasets API." \
  --cloud-api=false \
  --distribution-name="com.google.maps:google-maps-mapsplatformdatasets"
```

2023-02-14 16:37 UTC, suztomo requested changes
I may have to rewrite the generation script. No need to take action from you.

2023-02-14 16:37 UTC, suztomo commented on java-maps-mapsplatformdatasets/grpc-google-maps-mapsplatformdatasets-v1alpha/pom.xml
> +  <groupId>com.google.api.grpc</groupId>
This didn't became maps...

2023-02-24 19:32 UTC, suztomo commented
@emmileaf Once https://github.com/googleapis/synthtool/pull/1770 is merged and you get necessary information via b/264293181, would you recreate the pull request?

2023-02-24 19:32 UTC, closed without merging

2023-02-24 19:41 UTC, emmileaf commented
> @emmileaf Once [googleapis/synthtool#1770](https://github.com/googleapis/synthtool/pull/1770) is merged and you get necessary information via b/264293181, would you recreate the pull request?

@suztomo Sounds good, thank you for the heads up!